package  com.cemedo.data;
// Generated 1 juin 2022 � 14:01:29 by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Id;

/**
 * Facturepatient generated by hbm2java
 */
@Entity
@Table(name = "facturepatient", catalog = "heroku_88ae11bd39df693")
public class Facturepatient implements java.io.Serializable {

	private int numeroFacture;
	private Medecin medecin;
	private Patient patient;
	private Date dateFacture;
	private double montantFacture;

	public Facturepatient() {
	}

	public Facturepatient(int id, Medecin medecin, Patient patient, Date dateFacture,
			double montantFacture) {
		this.numeroFacture = id;
		this.medecin = medecin;
		this.patient = patient;
		this.dateFacture = dateFacture;
		this.montantFacture = montantFacture;
	}
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	public int getNumeroFacture() {
		return numeroFacture;
	}

	public void setNumeroFacture(int numeroFacture) {
		this.numeroFacture = numeroFacture;
	}
	

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Medecins_id_Medecins", nullable = false, insertable = false, updatable = false)
	public Medecin getMedecin() {
		return this.medecin;
	}

	public void setMedecin(Medecin medecin) {
		this.medecin = medecin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Patients_id_Patients", nullable = false, insertable = false, updatable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_Facture", nullable = false, length = 10)
	public Date getDateFacture() {
		return this.dateFacture;
	}

	public void setDateFacture(Date dateFacture) {
		this.dateFacture = dateFacture;
	}

	@Column(name = "montant_Facture", nullable = false, precision = 22, scale = 0)
	public double getMontantFacture() {
		return this.montantFacture;
	}

	public void setMontantFacture(double montantFacture) {
		this.montantFacture = montantFacture;
	}

}
